# .gitlab-ci.yml

stages:
  - build
  - test

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache


build:
  stage: build
  image: nodejs:16-slim
  tags:
    - cool-stuff-only
  script:
    - yarn
    - yarn run build
  artifacts:
    paths:
      - out

test:
  stage: test
  tags:
    - cool-stuff-only
  script:
    - cat out/index.html
