# .gitlab-ci.yml

stages:
  - build
  - test

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache


build:
  stage: build
  image: node:16-slim
  tags:
    - cool-stuff-only
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn run build
  artifacts:
    paths:
      - out

test:
  stage: test
  tags:
    - cool-stuff-only
  script:
    - cat out/index.html
