# .gitlab-ci.yml

stages:
  - build
  - test

build:
  stage: build
  # script: echo Run build ...
  script: echo Run build ...
  when: manual
  # allow_failure: false

test:
  stage: test
  script: echo test
  needs:
    - build
