# .gitlab-ci.yml

image: golang:1.19

build:
  parallel:
    matrix:
      - GOOS:
          - linux
          - darwin
          - windows
        FOO:
          - 1
          - 2
          - 3
        BAR:
          - a
          - b
          - c
        BAZ:
          - xxx
          - yyy
          - zzz
        xxx:
          - xxx
          - yyy
          - zzz
  script:
    - echo $GOOS $FOO $BAR $BAZ $xxx
