# .gitlab-ci.yml

image: sikalabs/ci

stages:
  - build
  - test

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .yarn-cache


build:
  stage: build
  tags:
    - cool-stuff-only
  script:
    - slu generate-files tree -c 100 -p out
  artifacts:
    paths:
      - out

build2:
  stage: build
  tags:
    - cool-stuff-only
  script:
    - slu generate-files tree -c 100 -p out2
  artifacts:
    paths:
      - out2

build32:
  stage: build
  tags:
    - cool-stuff-only
  script:
    - slu generate-files tree -c 100 -p out3
  artifacts:
    paths:
      - out3

test:
  stage: test
  tags:
    - cool-stuff-only
  script:
    - echo out/index.html
  dependencies: []


test2:
  stage: test
  tags:
    - cool-stuff-only
  script:
    - echo out/index.html
  dependencies: []

test4:
  stage: test
  tags:
    - cool-stuff-only
  script:
    - echo out/index.html
