job:
  script: echo "Hello, Rules!"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BEFORE_SHA == 0000000000000000000000000000000000000000
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
