stages:
  - deploy dev
  - deploy prod

.dev:
  stage: deploy dev
  variables:
    ENV: dev

.prod:
  stage: deploy prod
  variables:
    ENV: prod

.build:
  script: echo Build $ENV

.deploy:
  script: echo Deploy $ENV

build dev:
  extends:
    - .build
    - .dev
  retry: 2

build prod:
  extends:
    - .build
    - .prod

deploy dev:
  extends:
    - .deploy
    - .dev

deploy prod:
  extends:
    - .deploy
    - .prod
