stages:
  - a
  - b

a:
  stage: a
  script:
    - export MY_FOO=foo
    - MY_BAR=bar
    - env | grep MY_ > .env
  artifacts:
    paths:
      - .env

b:
  stage: b
  script:
    - export $(cat .env | xargs)
    - env | grep MY_
