# .gitlab-ci.yml

image: golang:1.19

build:
  parallel:
    matrix:
      - GOOS:
          - linux
          - darwin
          - windows
        GOARCH:
          - amd64
          - arm64
          - x86
  artifacts:
    paths:
      - hello-${GOOS}-${GOARCH}
  script:
    - go build -o hello-${GOOS}-${GOARCH} main.go
